/**
 * Executive Vault — mock dataset (Phase 3 prototype).
 *
 * Every value here is illustrative sample data written for this prototype.
 * NONE of it comes from a real Google Drive account, and no code in this
 * app makes a network call of any kind — see README.md. Google Drive
 * URLs/paths below are plausible-looking placeholders only.
 *
 * Loaded before app.js via a plain <script> tag (no bundler, no modules —
 * matches apps/executive-briefing's convention). Declares exactly one
 * global: window.VAULT_DATA. Everything else is wrapped in an IIFE so it
 * cannot collide with app.js's own top-level `const` declarations, which
 * destructure these same field names back out of window.VAULT_DATA — two
 * top-level `const`s with the same name in the same shared script scope
 * would otherwise be a SyntaxError.
 */
(function () {

const CLASSIFICATIONS = [
  { id: "highly-confidential", label: "Highly Confidential", cls: "tier-hc",
    test: "Board, shareholder, investment, legal privilege, or sensitive executive matters." },
  { id: "confidential", label: "Confidential", cls: "tier-c",
    test: "Named-individual HR/personnel data, contract terms, or client-sensitive commercial detail." },
  { id: "restricted", label: "Restricted", cls: "tier-r",
    test: "Internal project, operational or management material not for general circulation." },
  { id: "controlled", label: "Controlled", cls: "tier-ct",
    test: "Internal working documentation with a defined but wider internal circulation." },
  { id: "general", label: "General", cls: "tier-g",
    test: "Ordinary internal or reference material with no particular sensitivity." },
];

const STATUSES = [
  "Draft", "Working Draft", "Internal Review", "Management Review", "Client Review",
  "Pending Information", "Approved", "Final", "Issued", "Superseded", "Archived",
];

const FUNCTIONS = [
  "Executive Office", "Governance & Strategy", "Legal & Compliance",
  "Human Resources", "Finance & Investment", "Operations", "Research & Reference",
];

const ENGAGEMENTS = [
  {
    id: "vt-worldwide", code: "VT", name: "VT Worldwide", type: "client", status: "active",
    owner: "Me", pinned: true,
    summary: "Group-wide HR transformation and policy modernisation engagement, running since Q2 2026.",
    contacts: [
      { name: "Ravi Menon", role: "Group CHRO (client sponsor)" },
      { name: "Aisha Rahman", role: "HR Transformation Lead" },
    ],
    keyDates: [
      { label: "Engagement renewal", date: "2027-01-31" },
      { label: "HR-025 client sign-off due", date: "2026-09-30" },
    ],
    workstreams: ["HR Transformation", "Policy Framework"],
    driveFolder: "Clients & Engagements / VT Worldwide",
  },
  {
    id: "mre-asia", code: "MRE", name: "MRE Asia", type: "client", status: "active",
    owner: "Me", pinned: true,
    summary: "Advisory on a group-wide HR operating model, proposal stage.",
    contacts: [{ name: "Daniel Foo", role: "COO, MRE Asia" }],
    keyDates: [{ label: "Proposal decision expected", date: "2026-10-10" }],
    workstreams: ["Operating Model Design"],
    driveFolder: "Clients & Engagements / MRE Asia",
  },
  {
    id: "nusantara", code: "NUS", name: "Nusantara Project", type: "client", status: "active",
    owner: "Me", pinned: false,
    summary: "Strategic advisory engagement for the Nusantara regional expansion programme.",
    contacts: [{ name: "Wulan Sari", role: "Programme Director" }],
    keyDates: [{ label: "Executive summary review", date: "2026-09-25" }],
    workstreams: ["Strategic Advisory"],
    driveFolder: "Clients & Engagements / Nusantara Project",
  },
  {
    id: "sve-gep", code: "SVEGIP", name: "SVE Group Enterprise Platform", type: "project", status: "active",
    owner: "Me", pinned: true,
    summary: "Internal programme consolidating SVEGIP and shared enterprise services into one platform.",
    contacts: [{ name: "Eric Tang", role: "Executive Sponsor" }],
    keyDates: [{ label: "Management review due", date: "2026-09-28" }],
    workstreams: ["Platform Architecture", "Management Reporting"],
    driveFolder: "Projects & Programmes / SVE Group Enterprise Platform",
  },
  {
    id: "internal-governance", code: "INT", name: "Internal Governance", type: "project", status: "active",
    owner: "Me", pinned: false,
    summary: "Group governance, board administration, and internal policy ownership — not tied to one client.",
    contacts: [{ name: "Board Secretariat", role: "Coordination" }],
    keyDates: [{ label: "Board calendar refresh", date: "2026-11-01" }],
    workstreams: ["Board & Governance", "Group Policy"],
    driveFolder: "Projects & Programmes / Internal Governance",
  },
];

// documents: the single source of truth for every screen.
// classified:false => sits only in the Executive Inbox until filed.
const DOCUMENTS = [
  {
    id: "d01", docId: "HR-124", title: "Lark Digital Acknowledgement Workflow Specification",
    engagementId: "vt-worldwide", workstream: "HR Transformation", function: "Human Resources",
    docType: "Policy", version: "v0.1", versionChain: ["v0.1"], status: "Working Draft",
    confidentiality: "controlled", jurisdiction: "Malaysia", owner: "Me", reviewer: null,
    created: "2026-09-10", modified: "2026-09-18", reviewDate: "2026-09-29", starred: true,
    classified: true, tags: ["onboarding", "e-signature"],
    driveUrl: "https://drive.google.com/file/d/mock-hr124/view",
    drivePath: "Clients & Engagements / VT Worldwide / 03 – Working Documents / HR Transformation",
    notes: "First draft of the digital acknowledgement workflow for the Lark HR system rollout.",
  },
  {
    id: "d02", docId: "HR-025", title: "Resignation, Termination & Offboarding Policy",
    engagementId: "vt-worldwide", workstream: "Policy Framework", function: "Human Resources",
    docType: "Policy", version: "v0.4", versionChain: ["v0.1", "v0.2", "v0.3", "v0.4"], status: "Client Review",
    confidentiality: "confidential", jurisdiction: "Malaysia", owner: "Me", reviewer: "Ravi Menon",
    created: "2026-06-02", modified: "2026-09-20", reviewDate: "2026-09-30", starred: true,
    classified: true, tags: ["offboarding"],
    driveUrl: "https://drive.google.com/file/d/mock-hr025/view",
    drivePath: "Clients & Engagements / VT Worldwide / 06 – Client Review & Feedback",
    notes: "Sent to Ravi for sign-off on 20 Sep; awaiting confirmation before v1.0 Final.",
  },
  {
    id: "d03", docId: "VT-HR-SET3", title: "VT Worldwide HR Company Policy Framework – Set 3",
    engagementId: "vt-worldwide", workstream: "Policy Framework", function: "Human Resources",
    docType: "Policy Set", version: "v1.0 Final", versionChain: ["v0.1", "v0.2", "v1.0 Final"], status: "Final",
    confidentiality: "restricted", jurisdiction: "Malaysia", owner: "Me", reviewer: null,
    created: "2026-04-01", modified: "2026-08-14", reviewDate: null, starred: false,
    classified: true, tags: [],
    driveUrl: "https://drive.google.com/file/d/mock-vthrset3/view",
    drivePath: "Clients & Engagements / VT Worldwide / 07 – Final / Issued",
    notes: "",
  },
  {
    id: "d04", docId: "VT-HR-026", title: "Working Time & Overtime Policy",
    engagementId: "vt-worldwide", workstream: "Policy Framework", function: "Human Resources",
    docType: "Policy", version: "v0.3", versionChain: ["v0.1", "v0.2", "v0.3"], status: "Internal Review",
    confidentiality: "restricted", jurisdiction: "Malaysia", owner: "Me", reviewer: null,
    created: "2026-08-05", modified: "2026-09-15", reviewDate: "2026-09-26", starred: false,
    classified: true, tags: ["overtime", "working time"],
    driveUrl: "https://drive.google.com/file/d/mock-vthr026/view",
    drivePath: "Clients & Engagements / VT Worldwide / 03 – Working Documents / Policy Framework",
    notes: "Malaysia overtime calculation clause under review with internal legal.",
  },
  {
    id: "d05", docId: "VT-LG-004", title: "Employment Contract Template (Malaysia)",
    engagementId: "vt-worldwide", workstream: "Policy Framework", function: "Legal & Compliance",
    docType: "Template", version: "v1.0 Final", versionChain: ["v1.0 Final"], status: "Final",
    confidentiality: "confidential", jurisdiction: "Malaysia", owner: "Me", reviewer: null,
    created: "2026-05-20", modified: "2026-05-20", reviewDate: null, starred: false,
    classified: true, tags: ["template"],
    driveUrl: "https://drive.google.com/file/d/mock-vtlg004/view",
    drivePath: "Clients & Engagements / VT Worldwide / 08 – Reference",
    notes: "",
  },
  {
    id: "d06", docId: "VT-GV-002", title: "Engagement Letter — HR Transformation Programme",
    engagementId: "vt-worldwide", workstream: null, function: "Governance & Strategy",
    docType: "Contract", version: "v1.0 Final", versionChain: ["v1.0 Final"], status: "Final",
    confidentiality: "confidential", jurisdiction: "Malaysia", owner: "Me", reviewer: null,
    created: "2026-02-01", modified: "2026-02-03", reviewDate: null, starred: false,
    classified: true, tags: [],
    driveUrl: "https://drive.google.com/file/d/mock-vtgv002/view",
    drivePath: "Clients & Engagements / VT Worldwide / 01 – Engagement & Scope",
    notes: "",
  },
  {
    id: "d07", docId: "VT-MT-014", title: "Steering Committee Minutes — September 2026",
    engagementId: "vt-worldwide", workstream: "HR Transformation", function: "Governance & Strategy",
    docType: "Minutes", version: null, versionChain: [], status: "Final",
    confidentiality: "restricted", jurisdiction: "Malaysia", owner: "Me", reviewer: null,
    created: "2026-09-16", modified: "2026-09-16", reviewDate: null, starred: false,
    classified: true, tags: ["steering committee"],
    driveUrl: "https://drive.google.com/file/d/mock-vtmt014/view",
    drivePath: "Clients & Engagements / VT Worldwide / 04 – Meetings & Correspondence",
    notes: "",
  },
  {
    id: "d08", docId: "MRE-HR-001", title: "HR Operating Model Proposal",
    engagementId: "mre-asia", workstream: "Operating Model Design", function: "Human Resources",
    docType: "Proposal", version: "v0.1", versionChain: ["v0.1"], status: "Working Draft",
    confidentiality: "restricted", jurisdiction: "Singapore", owner: "Me", reviewer: null,
    created: "2026-09-08", modified: "2026-09-17", reviewDate: "2026-10-05", starred: true,
    classified: true, tags: ["operating model"],
    driveUrl: "https://drive.google.com/file/d/mock-mrehr001/view",
    drivePath: "Clients & Engagements / MRE Asia / 03 – Working Documents",
    notes: "First-pass proposal for MRE Asia's regional HR operating model.",
  },
  {
    id: "d09", docId: "MRE-GV-002", title: "Fee Proposal & Engagement Letter",
    engagementId: "mre-asia", workstream: null, function: "Governance & Strategy",
    docType: "Contract", version: "v1.0 Final", versionChain: ["v1.0 Final"], status: "Final",
    confidentiality: "confidential", jurisdiction: "Singapore", owner: "Me", reviewer: null,
    created: "2026-08-20", modified: "2026-08-22", reviewDate: null, starred: false,
    classified: true, tags: [],
    driveUrl: "https://drive.google.com/file/d/mock-mregv002/view",
    drivePath: "Clients & Engagements / MRE Asia / 01 – Engagement & Scope",
    notes: "",
  },
  {
    id: "d10", docId: "NUS-EX-001", title: "Nusantara — Executive Summary Note",
    engagementId: "nusantara", workstream: "Strategic Advisory", function: "Governance & Strategy",
    docType: "Note", version: "v1.0 Final", versionChain: ["v0.1", "v1.0 Final"], status: "Final",
    confidentiality: "general", jurisdiction: "ASEAN", owner: "Me", reviewer: null,
    created: "2026-08-01", modified: "2026-09-12", reviewDate: null, starred: false,
    classified: true, tags: [],
    driveUrl: "https://drive.google.com/file/d/mock-nusex001/view",
    drivePath: "Clients & Engagements / Nusantara Project / 07 – Final / Issued",
    notes: "",
  },
  {
    id: "d11", docId: "NUS-MT-002", title: "Nusantara Project Kickoff Minutes — September 2026",
    engagementId: "nusantara", workstream: "Strategic Advisory", function: "Governance & Strategy",
    docType: "Minutes", version: null, versionChain: [], status: "Final",
    confidentiality: "restricted", jurisdiction: "ASEAN", owner: "Me", reviewer: null,
    created: "2026-09-04", modified: "2026-09-04", reviewDate: null, starred: false,
    classified: true, tags: ["kickoff"],
    driveUrl: "https://drive.google.com/file/d/mock-nusmt002/view",
    drivePath: "Clients & Engagements / Nusantara Project / 04 – Meetings & Correspondence",
    notes: "",
  },
  {
    id: "d12", docId: "SVEGIP-MG-001", title: "SVE Group Enterprise Platform — Management Review",
    engagementId: "sve-gep", workstream: "Management Reporting", function: "Governance & Strategy",
    docType: "Report", version: "v0.1", versionChain: ["v0.1"], status: "Internal Review",
    confidentiality: "restricted", jurisdiction: "Global", owner: "Me", reviewer: "Eric Tang",
    created: "2026-09-14", modified: "2026-09-19", reviewDate: "2026-09-28", starred: true,
    classified: true, tags: ["management review"],
    driveUrl: "https://drive.google.com/file/d/mock-svegipmg001/view",
    drivePath: "Projects & Programmes / SVE Group Enterprise Platform / 03 – Working Documents",
    notes: "Awaiting Eric's review before circulation to the wider steering group.",
  },
  {
    id: "d13", docId: "SVEGIP-GV-002", title: "Enterprise Architecture Briefing Notes",
    engagementId: "sve-gep", workstream: "Platform Architecture", function: "Governance & Strategy",
    docType: "Report", version: "v1.0 Final", versionChain: ["v0.1", "v1.0 Final"], status: "Final",
    confidentiality: "restricted", jurisdiction: "Global", owner: "Me", reviewer: null,
    created: "2026-08-10", modified: "2026-08-28", reviewDate: null, starred: false,
    classified: true, tags: [],
    driveUrl: "https://drive.google.com/file/d/mock-svegipgv002/view",
    drivePath: "Projects & Programmes / SVE Group Enterprise Platform / 07 – Final / Issued",
    notes: "",
  },
  {
    id: "d14", docId: "INT-GV-001", title: "Board Governance Calendar 2026",
    engagementId: "internal-governance", workstream: "Board & Governance", function: "Governance & Strategy",
    docType: "Register", version: "v1.0 Final", versionChain: ["v1.0 Final"], status: "Final",
    confidentiality: "highly-confidential", jurisdiction: "Global", owner: "Me", reviewer: null,
    created: "2026-01-05", modified: "2026-09-01", reviewDate: "2026-11-01", starred: false,
    classified: true, tags: ["board"],
    driveUrl: "https://drive.google.com/file/d/mock-intgv001/view",
    drivePath: "Projects & Programmes / Internal Governance / 08 – Reference",
    notes: "",
  },
  {
    id: "d15", docId: "INT-HR-010", title: "Group Performance Management Framework",
    engagementId: "internal-governance", workstream: "Group Policy", function: "Human Resources",
    docType: "Policy", version: "v0.2", versionChain: ["v0.1", "v0.2"], status: "Working Draft",
    confidentiality: "controlled", jurisdiction: "Global", owner: "Me", reviewer: null,
    created: "2026-04-18", modified: "2026-05-12", reviewDate: "2026-06-01", starred: false,
    classified: true, tags: ["performance management"],
    driveUrl: "https://drive.google.com/file/d/mock-inthr010/view",
    drivePath: "Human Resources & Org",
    notes: "Stalled since May — needs a decision on whether this restarts or is superseded.",
  },
  {
    id: "d16", docId: "INT-FN-003", title: "Labuan Fund Structuring Note",
    engagementId: "internal-governance", workstream: null, function: "Finance & Investment",
    docType: "Note", version: "v0.1", versionChain: ["v0.1"], status: "Working Draft",
    confidentiality: "highly-confidential", jurisdiction: "Labuan", owner: "Me", reviewer: null,
    created: "2026-09-02", modified: "2026-09-11", reviewDate: "2026-09-25", starred: true,
    classified: true, tags: ["fund structuring"],
    driveUrl: "https://drive.google.com/file/d/mock-intfn003/view",
    drivePath: "Finance & Investment",
    notes: "",
  },
  {
    id: "d17", docId: "INT-LG-005", title: "Group Data Protection Policy",
    engagementId: "internal-governance", workstream: "Group Policy", function: "Legal & Compliance",
    docType: "Policy", version: "v1.0 Final", versionChain: ["v1.0 Final"], status: "Final",
    confidentiality: "general", jurisdiction: "Global", owner: "Me", reviewer: null,
    created: "2026-03-01", modified: "2026-03-01", reviewDate: null, starred: false,
    classified: true, tags: [],
    driveUrl: "https://drive.google.com/file/d/mock-intlg005/view",
    drivePath: "Legal & Compliance",
    notes: "",
  },
  {
    id: "d18", docId: "HR-124", title: "Lark Digital Acknowledgement Workflow Spec (copy)",
    engagementId: "vt-worldwide", workstream: "HR Transformation", function: "Human Resources",
    docType: "Policy", version: "v0.1", versionChain: ["v0.1"], status: "Working Draft",
    confidentiality: "controlled", jurisdiction: "Malaysia", owner: "Me", reviewer: null,
    created: "2026-09-10", modified: "2026-09-10", reviewDate: null, starred: false,
    classified: true, tags: [],
    driveUrl: "https://drive.google.com/file/d/mock-hr124-copy/view",
    drivePath: "Clients & Engagements / VT Worldwide / 02 – Information Received",
    notes: "",
    possibleDuplicateOf: "d01",
  },
  {
    id: "d19", docId: null, title: "VT Worldwide – Employee Handbook Draft",
    engagementId: "vt-worldwide", workstream: "Policy Framework", function: "Human Resources",
    docType: "Policy", version: null, versionChain: [], status: "Working Draft",
    confidentiality: "controlled", jurisdiction: "Malaysia", owner: "Me", reviewer: null,
    created: "2026-07-01", modified: "2026-07-01", reviewDate: null, starred: false,
    classified: true, tags: [],
    driveUrl: "https://drive.google.com/file/d/mock-vthandbook/view",
    drivePath: "Clients & Engagements / VT Worldwide / 03 – Working Documents / Policy Framework",
    notes: "",
  },
  {
    id: "d20", docId: "INT-OP-007", title: "Business Continuity Plan Update",
    engagementId: "internal-governance", workstream: null, function: "Operations",
    docType: "Report", version: "v0.2", versionChain: ["v0.1", "v0.2"], status: "Working Draft",
    confidentiality: "restricted", jurisdiction: "Global", owner: "Me", reviewer: null,
    created: "2026-04-02", modified: "2026-05-09", reviewDate: "2026-06-01", starred: false,
    classified: true, tags: [],
    driveUrl: "https://drive.google.com/file/d/mock-intop007/view",
    drivePath: "Operations & Administration",
    notes: "No activity since May — candidate for either restart or archive.",
  },
  {
    id: "d21", docId: "VT-HR-018", title: "Legacy Leave Policy (Superseded)",
    engagementId: "vt-worldwide", workstream: "Policy Framework", function: "Human Resources",
    docType: "Policy", version: "v2.3", versionChain: ["v2.0", "v2.1", "v2.2", "v2.3"], status: "Superseded",
    confidentiality: "restricted", jurisdiction: "Malaysia", owner: "Me", reviewer: null,
    created: "2024-01-10", modified: "2026-04-01", reviewDate: null, starred: false,
    classified: true, tags: [],
    driveUrl: "https://drive.google.com/file/d/mock-vthr018/view",
    drivePath: "Clients & Engagements / VT Worldwide / 99 – Archive",
    notes: "Superseded by VT Worldwide HR Company Policy Framework — Set 3.",
  },
  {
    id: "d22", docId: "TPL-001", title: "Engagement Letter Template",
    engagementId: null, workstream: null, function: "Research & Reference",
    docType: "Template", version: "v1.0 Final", versionChain: ["v1.0 Final"], status: "Final",
    confidentiality: "general", jurisdiction: "Global", owner: "Me", reviewer: null,
    created: "2026-01-01", modified: "2026-01-01", reviewDate: null, starred: false,
    classified: true, tags: ["template"],
    driveUrl: "https://drive.google.com/file/d/mock-tpl001/view",
    drivePath: "Templates & Reference",
    notes: "",
  },
  {
    id: "d23", docId: "TPL-002", title: "Board Paper Template",
    engagementId: null, workstream: null, function: "Research & Reference",
    docType: "Template", version: "v1.0 Final", versionChain: ["v1.0 Final"], status: "Final",
    confidentiality: "general", jurisdiction: "Global", owner: "Me", reviewer: null,
    created: "2026-01-01", modified: "2026-01-01", reviewDate: null, starred: false,
    classified: true, tags: ["template"],
    driveUrl: "https://drive.google.com/file/d/mock-tpl002/view",
    drivePath: "Templates & Reference",
    notes: "",
  },
  {
    id: "d24", docId: null, title: "Scan_2026-09-19.pdf",
    engagementId: null, workstream: null, function: null,
    docType: null, version: null, versionChain: [], status: "Working Draft",
    confidentiality: "general", jurisdiction: null, owner: "Me", reviewer: null,
    created: "2026-09-19", modified: "2026-09-19", reviewDate: null, starred: false,
    classified: false, tags: [],
    driveUrl: "https://drive.google.com/file/d/mock-scan0919/view",
    drivePath: "Executive Inbox",
    notes: "",
  },
  {
    id: "d25", docId: null, title: "IMG_Board_Pack_Sept.pdf",
    engagementId: null, workstream: null, function: null,
    docType: null, version: null, versionChain: [], status: "Working Draft",
    confidentiality: "general", jurisdiction: null, owner: "Me", reviewer: null,
    created: "2026-09-20", modified: "2026-09-20", reviewDate: null, starred: false,
    classified: false, tags: [],
    driveUrl: "https://drive.google.com/file/d/mock-imgboardpack/view",
    drivePath: "Executive Inbox",
    notes: "",
  },
];

const MEETINGS = [
  { id: "m1", title: "Steering Committee — September 2026", engagementId: "vt-worldwide", date: "2026-09-16", documentId: "d07",
    decisions: ["Approved v0.3 of the Working Time & Overtime Policy for internal legal review."] },
  { id: "m2", title: "Nusantara Project Kickoff", engagementId: "nusantara", date: "2026-09-04", documentId: "d11",
    decisions: ["Confirmed Strategic Advisory as the sole workstream for Phase 1."] },
];

const TASKS = [
  { id: "t1", title: "Confirm VT overtime policy wording with internal legal", engagementId: "vt-worldwide", due: "2026-09-26", done: false, documentId: "d04" },
  { id: "t2", title: "Send MRE Operating Model proposal v0.2 to Daniel Foo", engagementId: "mre-asia", due: "2026-09-30", done: false, documentId: "d08" },
  { id: "t3", title: "Get Ravi Menon's sign-off on HR-025 v0.4", engagementId: "vt-worldwide", due: "2026-09-30", done: false, documentId: "d02" },
  { id: "t4", title: "Circulate Management Review to Eric Tang", engagementId: "sve-gep", due: "2026-09-28", done: false, documentId: "d12" },
  { id: "t5", title: "Decide: restart or archive Business Continuity Plan Update", engagementId: "internal-governance", due: "2026-09-27", done: false, documentId: "d20" },
];

window.VAULT_DATA = { CLASSIFICATIONS, STATUSES, FUNCTIONS, ENGAGEMENTS, DOCUMENTS, MEETINGS, TASKS, TODAY: "2026-09-21" };

})();
