(() => {
const q=s=>document.querySelector(s),body=()=>q('#portalBody');
const setHead=(k,t)=>{if(q('#portalKicker'))q('#portalKicker').textContent=k;if(q('#portalTitle'))q('#portalTitle').textContent=t};
const status=(t,c='built')=>`<span class="suite-status ${c}">${t}</span>`;
const setActive=key=>document.querySelectorAll('.portal-side .portal-nav').forEach(n=>n.classList.toggle('active',n.dataset.view===key||n.dataset.suitePlanned===key));
const setFooter=text=>{const f=q('.portal-footer span:first-child');if(f)f.textContent=text};
const flow=()=>`<div class="suite-flow"><div><b>INFORMATION</b><span>Governed records</span></div><i>→</i><div><b>INTELLIGENCE</b><span>Analysis & signals</span></div><i>→</i><div><b>MANAGEMENT INSIGHT</b><span>Executive context</span></div><i>→</i><div><b>DECISION</b><span>Controlled decision</span></div><i>→</i><div><b>IMPLEMENTATION</b><span>Action & ownership</span></div><i>→</i><div><b>OUTCOME</b><span>Monitoring</span></div></div>`;
function vault(tab='overview'){
 setHead('MANAGEMENT APPLICATIONS / INTELLIGENCE','Data Vault & Intelligence');setActive('vault');setFooter('Executive preview · management information & intelligence');
 const nav=`<div class="suite-tabs"><button data-suite-vault="overview" class="${tab==='overview'?'active':''}">Overview</button><button data-suite-vault="vault" class="${tab==='vault'?'active':''}">Data Vault</button><button data-suite-vault="intelligence" class="${tab==='intelligence'?'active':''}">Intelligence</button><button data-suite-vault="insight" class="${tab==='insight'?'active':''}">Management Insight</button><button data-suite-vault="decision" class="${tab==='decision'?'active':''}">Decision & Outcome</button></div>`;let content='';
 if(tab==='overview')content=`<div class="suite-hero"><div><span>MANAGEMENT INFORMATION & INTELLIGENCE WORKSPACE</span><h2>From Information to Intelligence</h2><p>A connected management flow that moves governed information through intelligence, insight and decision-making, progressively into implementation and monitored outcomes.</p></div>${status('EXECUTIVE PREVIEW','preview')}</div>${flow()}<div class="suite-card-grid"><button data-suite-vault="vault" class="suite-card"><span>GOVERNED INFORMATION</span><h3>SVE Data Vault</h3><p>Server-side foundation for controlled records and evidence.</p>${status('FOUNDATION BUILT')}</button><button data-suite-vault="intelligence" class="suite-card"><span>ANALYSIS</span><h3>Intelligence Workspace</h3><p>Policy, news, risk and evidence signals prepared for management use.</p>${status('NEXT DEVELOPMENT','next')}</button><button data-suite-vault="insight" class="suite-card"><span>MANAGEMENT</span><h3>Management Insight</h3><p>Translate intelligence into executive context and management attention.</p>${status('NEXT INTEGRATION','partial')}</button><button data-suite-vault="decision" class="suite-card"><span>ACTION</span><h3>Decision & Outcome</h3><p>Connect insight to decisions, implementation ownership and monitored outcomes.</p>${status('PARTIALLY BUILT','partial')}</button></div>`;
 if(tab==='vault')content=`<div class="suite-section-head"><div><h2>SVE Data Vault</h2><p>The governed information foundation beneath the management intelligence flow.</p></div>${status('NEXT INTEGRATION','partial')}</div><div class="suite-metrics"><div><span>SERVER-SIDE RECORDS</span><strong>Foundation Built</strong></div><div><span>ACCESS CONTROL</span><strong>Foundation Built</strong></div><div><span>AUDITABILITY</span><strong>Foundation Built</strong></div><div><span>VISIBLE WORKSPACE</span><strong>Next Integration</strong></div></div><div class="suite-panel"><h3>Information Domains</h3><div class="suite-list"><div><b>Documents & Data Rooms</b><span>Controlled business information and evidence</span></div><div><b>Policy Monitor</b><span>Policy and regulatory source monitoring</span></div><div><b>News Monitor</b><span>External developments relevant to management</span></div><div><b>Risk & Escalation</b><span>Items requiring attention and routing</span></div><div><b>Report Data Packs</b><span>Governed evidence prepared for reporting</span></div></div></div>`;
 if(tab==='intelligence')content=`<div class="suite-section-head"><div><h2>Intelligence Workspace</h2><p>Planned analytical layer above governed information. This preview demonstrates the intended operating model, not a live intelligence engine.</p></div>${status('NEXT DEVELOPMENT','next')}</div><div class="suite-card-grid three"><div class="suite-card"><span>SIGNAL</span><h3>Policy & Regulatory</h3><p>Identify relevant changes and connect them to internal policies, entities and management owners.</p></div><div class="suite-card"><span>SIGNAL</span><h3>News & Market</h3><p>Capture external developments and distinguish information from management-relevant intelligence.</p></div><div class="suite-card"><span>RISK</span><h3>Risk & Escalation</h3><p>Route material intelligence for management attention based on authority and access.</p></div></div>`;
 if(tab==='insight')content=`<div class="suite-section-head"><div><h2>Management Insight</h2><p>The point at which analysed information becomes management context.</p></div>${status('NEXT INTEGRATION','partial')}</div><div class="suite-panel"><h3>Illustrative Management Insight</h3><div class="insight-layout"><div><span>SUBJECT</span><strong>Enterprise Platform Integration</strong><p>Multiple platform foundations are now established. The next management question is sequencing operational integration without disrupting the existing SVEGIP environment.</p></div><div><span>MANAGEMENT ATTENTION</span><strong>Integration sequencing</strong><p>Prioritise shared identity, governed data and workflow connections before expanding transactional modules.</p></div><div><span>PROPOSED ROUTE</span><strong>Decision Tracker</strong><p>Record management direction, accountable owner and implementation milestone.</p></div></div></div>`;
 if(tab==='decision')content=`<div class="suite-section-head"><div><h2>Decision → Implementation → Outcome</h2><p>Close the management loop instead of allowing insight to remain informational only.</p></div>${status('PARTIALLY BUILT','partial')}</div>${flow()}<div class="suite-panel"><table class="suite-table"><tr><th>Management Item</th><th>Decision Status</th><th>Implementation</th><th>Outcome</th></tr><tr><td>Enterprise Platform Integration</td><td>Management Review</td><td>Roadmap sequencing</td><td>Monitoring to follow</td></tr><tr><td>People / HRMS Foundation</td><td>Foundation established</td><td>Application experience in preview</td><td>Operational integration pending</td></tr></table></div>`;
 body().innerHTML=`${nav}<div class="suite-content">${content}</div>`;
}
function finance(tab='overview'){
 setHead('RESTRICTED FINANCE SYSTEM','SVE Accounting Pro');setActive('finance');setFooter('Executive preview · restricted finance system');
 const nav=`<div class="suite-tabs finance-tabs"><button data-suite-finance="overview" class="${tab==='overview'?'active':''}">Finance Overview</button><button data-suite-finance="accounting" class="${tab==='accounting'?'active':''}">Accounting</button><button data-suite-finance="payroll" class="${tab==='payroll'?'active':''}">Payroll Management</button><button data-suite-finance="claims" class="${tab==='claims'?'active':''}">Claims & Payables</button><button data-suite-finance="reporting" class="${tab==='reporting'?'active':''}">Reporting</button></div>`;let content='';
 if(tab==='overview')content=`<div class="suite-hero finance-hero"><div><span>SVE GROUP INTEGRATED FINANCE & BUSINESS SYSTEMS</span><h2>SVE Accounting Pro</h2><p>A restricted multi-entity finance system designed to connect accounting, payroll management, claims and management reporting.</p></div>${status('FOUNDATION BUILT')}</div><div class="suite-metrics"><div><span>ENTITIES</span><strong>Multi-Entity Ready</strong></div><div><span>CURRENCIES</span><strong>MYR / SGD / USD</strong></div><div><span>PAYROLL</span><strong>Inside Accounting Pro</strong></div><div><span>ACCESS</span><strong>Restricted Finance</strong></div></div><div class="suite-card-grid three"><button data-suite-finance="accounting" class="suite-card"><span>CORE FINANCE</span><h3>Accounting</h3><p>Transactions, ledgers and entity-aware multi-currency finance records.</p></button><button data-suite-finance="payroll" class="suite-card"><span>PEOPLE → FINANCE</span><h3>Payroll Management</h3><p>Payroll processing receives controlled HR master and compensation inputs.</p></button><button data-suite-finance="reporting" class="suite-card"><span>MANAGEMENT</span><h3>Finance Reporting</h3><p>Entity, group and multi-currency reporting architecture.</p></button></div>`;
 if(tab==='accounting')content=`<div class="suite-section-head"><div><h2>Accounting</h2><p>Multi-entity, multi-currency accounting architecture with controlled legal-entity context.</p></div>${status('FOUNDATION BUILT')}</div><div class="suite-panel"><table class="suite-table"><tr><th>Entity</th><th>Jurisdiction</th><th>Primary Currency</th><th>Supported Transaction Currencies</th><th>Context</th></tr><tr><td>SVE International Pte. Ltd.</td><td>Singapore</td><td>SGD</td><td>SGD / USD / MYR</td><td>Group Headquarters</td></tr><tr><td>SVE International Sdn. Bhd.</td><td>Malaysia</td><td>MYR</td><td>MYR / SGD / USD</td><td>Malaysian operating entity</td></tr><tr><td>SK Lai & Partners</td><td>Malaysia</td><td>MYR</td><td>MYR / SGD / USD</td><td>Distinct legal / professional entity</td></tr></table></div>`;
 if(tab==='payroll')content=`<div class="suite-section-head"><div><h2>Payroll Management</h2><p>Payroll is a controlled finance function within SVE Accounting Pro — not a general employee portal application.</p></div>${status('NEXT DEVELOPMENT','next')}</div><div class="suite-flow compact"><div><b>HRMS</b><span>Employee Master</span></div><i>→</i><div><b>PAYROLL</b><span>Gross-to-net processing</span></div><i>→</i><div><b>ACCOUNTING</b><span>Posting & liability</span></div><i>→</i><div><b>MY SVE</b><span>Approved payslip</span></div></div><div class="suite-card-grid three"><div class="suite-card"><span>INPUT</span><h3>Controlled Employee Data</h3><p>Entity, position, compensation and employment status originate from HRMS.</p></div><div class="suite-card"><span>PROCESS</span><h3>Payroll Run</h3><p>Jurisdiction-aware payroll periods, calculations, approvals and statutory outputs.</p></div><div class="suite-card"><span>OUTPUT</span><h3>Payslip & Posting</h3><p>Approved payslips surface to employees while accounting entries remain finance-controlled.</p></div></div>`;
 if(tab==='claims')content=`<div class="suite-section-head"><div><h2>Claims & Payables</h2><p>Employee iClaims will connect approved claims into the finance workflow without exposing Accounting Pro to ordinary employees.</p></div>${status('NEXT DEVELOPMENT','next')}</div><div class="suite-flow compact"><div><b>MY SVE</b><span>Submit iClaim</span></div><i>→</i><div><b>WORKFLOW</b><span>Approval</span></div><i>→</i><div><b>FINANCE</b><span>Verification</span></div><i>→</i><div><b>ACCOUNTING</b><span>Payment & posting</span></div></div>`;
 if(tab==='reporting')content=`<div class="suite-section-head"><div><h2>Finance Reporting</h2><p>Management reporting is designed around authorised entity, group and multi-currency views.</p></div>${status('FOUNDATION BUILT')}</div><div class="suite-card-grid three"><div class="suite-card"><span>ENTITY</span><h3>Entity Reporting</h3><p>Legal-entity financial position and transaction reporting in applicable base and transaction currencies.</p></div><div class="suite-card"><span>GROUP</span><h3>Management Summary</h3><p>Authorised cross-entity management view with MYR, SGD and USD support without removing entity boundaries.</p></div><div class="suite-card"><span>AUDIT</span><h3>Control & Traceability</h3><p>Approval, posting and change history designed for traceable finance operations.</p></div></div>`;
 body().innerHTML=`${nav}<div class="suite-content">${content}</div>`;
}
function planned(kind){setHead('MY WORKSPACE / EMPLOYEE',kind==='payslip'?'My Payslips':'iClaims');setActive(kind);setFooter(`Executive preview · employee self-service · next development`);body().innerHTML=`<div class="suite-hero"><div><span>EMPLOYEE SELF-SERVICE</span><h2>${kind==='payslip'?'My Payslips':'iClaims'}</h2><p>${kind==='payslip'?'Employees will view and download their own approved payslips here. Payroll processing itself remains inside restricted SVE Accounting Pro.':'Employees will submit and track their own claims here. Approved claims will flow through controlled workflow into Finance and Accounting Pro.'}</p></div>${status('NEXT DEVELOPMENT','next')}</div><div class="suite-panel"><h3>Planned employee experience</h3><p class="suite-copy">This screen intentionally shows the product boundary now, without presenting unbuilt transactional functionality as operational.</p></div>`}
function upgradeNav(){document.querySelectorAll('.portal-nav.disabled').forEach(b=>{if(b.textContent.includes('Payslips')){b.classList.remove('disabled');b.dataset.suitePlanned='payslip'}if(b.textContent.includes('iClaims')){b.classList.remove('disabled');b.dataset.suitePlanned='claims'}})}
document.addEventListener('click',e=>{const v=e.target.closest('[data-suite-vault]');if(v){e.preventDefault();e.stopImmediatePropagation();vault(v.dataset.suiteVault);return}const f=e.target.closest('[data-suite-finance]');if(f){e.preventDefault();e.stopImmediatePropagation();finance(f.dataset.suiteFinance);return}const p=e.target.closest('[data-suite-planned]');if(p){e.preventDefault();e.stopImmediatePropagation();planned(p.dataset.suitePlanned);return}const n=e.target.closest('[data-view="vault"]');if(n){e.preventDefault();e.stopImmediatePropagation();vault();return}const a=e.target.closest('[data-view="finance"]');if(a){e.preventDefault();e.stopImmediatePropagation();finance();return}},true);
upgradeNav();
})();