/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    insights: Insight;
    nusantaraViews: NusantaraView;
    marketStateEditions: MarketStateEdition;
    signals: Signal;
    themes: Theme;
    capabilities: Capability;
    legalPages: LegalPage;
    media: Media;
    users: User;
    auditLog: AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    insights: InsightsSelect<false> | InsightsSelect<true>;
    nusantaraViews: NusantaraViewsSelect<false> | NusantaraViewsSelect<true>;
    marketStateEditions: MarketStateEditionsSelect<false> | MarketStateEditionsSelect<true>;
    signals: SignalsSelect<false> | SignalsSelect<true>;
    themes: ThemesSelect<false> | ThemesSelect<true>;
    capabilities: CapabilitiesSelect<false> | CapabilitiesSelect<true>;
    legalPages: LegalPagesSelect<false> | LegalPagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    auditLog: AuditLogSelect<false> | AuditLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  /**
   * URL segment under /insights/. Changing it changes the public URL.
   */
  slug: string;
  title: string;
  subtitle: string;
  category:
    | 'Market Outlook'
    | 'Investment Perspectives'
    | 'Macro & Markets'
    | 'Alternative Investments'
    | 'Private Markets'
    | 'Governance & Allocation'
    | 'Research Notes';
  date: string;
  summary: string;
  executiveSummary?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  keyTakeaways?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  body?:
    | (
        | {
            text: string;
            /**
             * Short lower-case name used in the article’s contents list, e.g. “framing”.
             */
            anchor: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            ordered?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pullquote';
          }
        | {
            layer: 'data' | 'interpretation' | 'implication';
            title: string;
            body?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'layer';
          }
        | {
            caption: string;
            /**
             * Type each heading and press Enter.
             */
            columns?: string[] | null;
            rows?:
              | {
                  cells?: string[] | null;
                  id?: string | null;
                }[]
              | null;
            note?: string | null;
            /**
             * Optional: which research layer this table belongs to.
             */
            layer?: ('data' | 'interpretation' | 'implication') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'table';
          }
        | {
            caption: string;
            left: string;
            right: string;
            rows?:
              | {
                  leftText: string;
                  rightText: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'comparison';
          }
        | {
            caption: string;
            kind: 'line' | 'bar';
            /**
             * Type each label and press Enter, e.g. “Oct 25”.
             */
            xLabels?: string[] | null;
            series?:
              | {
                  /**
                   * Short lower-case name, e.g. “gold”.
                   */
                  seriesKey: string;
                  label: string;
                  values?: number[] | null;
                  id?: string | null;
                }[]
              | null;
            unit?: string | null;
            decimals: number;
            source: string;
            illustrative?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'chart';
          }
        | {
            scenario: {
              /**
               * Short lower-case name, e.g. “inflation-paths”.
               */
              scenarioKey: string;
              title: string;
              metric: string;
              unit?: string | null;
              decimals: number;
              baseYear: number;
              baseValue: number;
              years?: number[] | null;
              /**
               * e.g. quarters, instead of years.
               */
              periodLabels?: string[] | null;
              downside: {
                /**
                 * e.g. “Persistent”.
                 */
                label?: string | null;
                assumption: string;
                /**
                 * One value per period, in order. Leave empty to use a constant annual rate instead.
                 */
                values?: number[] | null;
                /**
                 * Only when no values per period are given.
                 */
                rate?: number | null;
              };
              base: {
                /**
                 * e.g. “Persistent”.
                 */
                label?: string | null;
                assumption: string;
                /**
                 * One value per period, in order. Leave empty to use a constant annual rate instead.
                 */
                values?: number[] | null;
                /**
                 * Only when no values per period are given.
                 */
                rate?: number | null;
              };
              upside: {
                /**
                 * e.g. “Persistent”.
                 */
                label?: string | null;
                assumption: string;
                /**
                 * One value per period, in order. Leave empty to use a constant annual rate instead.
                 */
                values?: number[] | null;
                /**
                 * Only when no values per period are given.
                 */
                rate?: number | null;
              };
              period: string;
              dataSource: string;
              methodology: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'scenario';
          }
        | {
            title: string;
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
      )[]
    | null;
  methodology?: string | null;
  sources?:
    | {
        label: string;
        detail?: string | null;
        /**
         * Only where the licence permits.
         */
        url?: string | null;
        provider?: string | null;
        publishedAt?: string | null;
        retrievedAt?: string | null;
        licensingNote?: string | null;
        methodology?: string | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  heroMotif: 'arcs' | 'lines' | 'grid' | 'bars' | 'rings';
  tags?: string[] | null;
  related?: (number | Insight)[] | null;
  markets?:
    | (
        | 'klci'
        | 'sti'
        | 'jci'
        | 'nikkei'
        | 'hsi'
        | 'spx'
        | 'nasdaq'
        | 'usdmyr'
        | 'usdsgd'
        | 'usdidr'
        | 'sgdmyr'
        | 'eurusd'
        | 'usdcnh'
        | 'usdjpy'
        | 'us10y'
        | 'us2y'
        | 'mgs10y'
        | 'jgb10y'
        | 'sgs10y'
        | 'gold'
        | 'silver'
        | 'brent'
        | 'cpo'
        | 'copper'
      )[]
    | null;
  themes?: (number | Theme)[] | null;
  assetClasses?:
    | (
        | 'Equities'
        | 'Fixed income'
        | 'Currencies'
        | 'Commodities'
        | 'Private credit'
        | 'Private markets'
        | 'Real assets'
        | 'Alternatives'
        | 'Multi-asset'
      )[]
    | null;
  capabilities?: (number | Capability)[] | null;
  marketStateDimensions?: ('growth' | 'rates' | 'liquidity' | 'risk' | 'currencies' | 'commodities')[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Lower numbers appear first where the website lists these items in a fixed order.
   */
  displayOrder?: number | null;
  /**
   * Editors: Draft or In review. Reviewers/Admins may approve and publish.
   */
  workflowStatus: 'draft' | 'review' | 'approved' | 'published' | 'archived';
  /**
   * Independent of workflow. Publishing does not change it. Only an Admin may confirm Approved corporate content.
   */
  contentClass: 'illustrative' | 'management_review' | 'approved_corporate';
  classificationConfirmedBy?: (number | null) | User;
  classificationConfirmedAt?: string | null;
  /**
   * Institutional byline, e.g. “Nusantara Investment Team”. Individual names only once approved.
   */
  author?: string | null;
  /**
   * After this date the item is withdrawn from the public site until re-reviewed.
   */
  reviewAt?: string | null;
  createdBy?: (number | null) | User;
  lastEditedBy?: (number | null) | User;
  submittedBy?: (number | null) | User;
  submittedAt?: string | null;
  approvedByUser?: (number | null) | User;
  approvedBy?: string | null;
  approvedAt?: string | null;
  approvedContentHash?: string | null;
  publishedAt?: string | null;
  /**
   * Set automatically when content changes. Shown on the website as the update date.
   */
  revisedAt?: string | null;
  /**
   * Preserved verbatim from the code-based content during migration. Never used to infer approval.
   */
  legacy?: {
    key?: string | null;
    status?: ('draft' | 'review' | 'approved' | 'published' | 'archived') | null;
    sample?: boolean | null;
    updatedAt?: string | null;
    importHash?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes".
 */
export interface Theme {
  id: number;
  /**
   * Stable id.
   */
  key: string;
  title: string;
  statement: string;
  /**
   * Curated research, in display order.
   */
  insights?: (number | Insight)[] | null;
  instruments?:
    | (
        | 'klci'
        | 'sti'
        | 'jci'
        | 'nikkei'
        | 'hsi'
        | 'spx'
        | 'nasdaq'
        | 'usdmyr'
        | 'usdsgd'
        | 'usdidr'
        | 'sgdmyr'
        | 'eurusd'
        | 'usdcnh'
        | 'usdjpy'
        | 'us10y'
        | 'us2y'
        | 'mgs10y'
        | 'jgb10y'
        | 'sgs10y'
        | 'gold'
        | 'silver'
        | 'brent'
        | 'cpo'
        | 'copper'
      )[]
    | null;
  indicators?:
    | (
        | 'am-assets'
        | 'am-alt-share'
        | 'pm-fundraising'
        | 'pm-undeployed'
        | 'pm-credit'
        | 'alt-real-assets'
        | 'alt-precious'
        | 'cf-portfolio'
        | 'cf-direct'
        | 'pw-pool'
        | 'pw-advised'
        | 'fo-formation'
        | 'inst-alts'
        | 'macro-growth'
        | 'macro-inflation'
        | 'macro-policy'
      )[]
    | null;
  /**
   * Lower numbers appear first where the website lists these items in a fixed order.
   */
  displayOrder?: number | null;
  /**
   * Editors: Draft or In review. Reviewers/Admins may approve and publish.
   */
  workflowStatus: 'draft' | 'review' | 'approved' | 'published' | 'archived';
  /**
   * Independent of workflow. Publishing does not change it. Only an Admin may confirm Approved corporate content.
   */
  contentClass: 'illustrative' | 'management_review' | 'approved_corporate';
  classificationConfirmedBy?: (number | null) | User;
  classificationConfirmedAt?: string | null;
  /**
   * Institutional byline, e.g. “Nusantara Investment Team”. Individual names only once approved.
   */
  author?: string | null;
  /**
   * After this date the item is withdrawn from the public site until re-reviewed.
   */
  reviewAt?: string | null;
  createdBy?: (number | null) | User;
  lastEditedBy?: (number | null) | User;
  submittedBy?: (number | null) | User;
  submittedAt?: string | null;
  approvedByUser?: (number | null) | User;
  approvedBy?: string | null;
  approvedAt?: string | null;
  approvedContentHash?: string | null;
  publishedAt?: string | null;
  /**
   * Set automatically when content changes. Shown on the website as the update date.
   */
  revisedAt?: string | null;
  /**
   * Preserved verbatim from the code-based content during migration. Never used to infer approval.
   */
  legacy?: {
    key?: string | null;
    status?: ('draft' | 'review' | 'approved' | 'published' | 'archived') | null;
    sample?: boolean | null;
    updatedAt?: string | null;
    importHash?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Editor: drafts and submits. Reviewer: approves and publishes. Admin: also users, settings and Approved corporate classification.
   */
  role: 'editor' | 'reviewer' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Descriptive capability content and relationships. New capabilities: Admins only. Investment products cannot be created here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capabilities".
 */
export interface Capability {
  id: number;
  /**
   * URL segment under /strategies/. Set by an Admin; changing it changes the public URL.
   */
  slug: string;
  name: string;
  /**
   * Governance lifecycle (Reviewers/Admins). “active-product” cannot be set here.
   */
  capabilityStatus: 'internal' | 'review' | 'public-capability' | 'active-product' | 'archived';
  /**
   * Public stage (Reviewers/Admins). “Active” cannot be set here.
   */
  stage: 'capability' | 'under-review' | 'strategy' | 'active' | 'future-development';
  summary: string;
  overview: string;
  approach: string;
  opportunitySet?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  riskConsiderations?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty until supplied.
   */
  timeHorizon?: string | null;
  characteristics?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  role: string;
  profile?: {
    liquidity?: ('0' | '1' | '2') | null;
    income?: ('0' | '1' | '2') | null;
    complexity?: ('0' | '1' | '2') | null;
    valuationFrequency?: ('0' | '1' | '2') | null;
  };
  markets?:
    | (
        | 'klci'
        | 'sti'
        | 'jci'
        | 'nikkei'
        | 'hsi'
        | 'spx'
        | 'nasdaq'
        | 'usdmyr'
        | 'usdsgd'
        | 'usdidr'
        | 'sgdmyr'
        | 'eurusd'
        | 'usdcnh'
        | 'usdjpy'
        | 'us10y'
        | 'us2y'
        | 'mgs10y'
        | 'jgb10y'
        | 'sgs10y'
        | 'gold'
        | 'silver'
        | 'brent'
        | 'cpo'
        | 'copper'
      )[]
    | null;
  indicators?:
    | (
        | 'am-assets'
        | 'am-alt-share'
        | 'pm-fundraising'
        | 'pm-undeployed'
        | 'pm-credit'
        | 'alt-real-assets'
        | 'alt-precious'
        | 'cf-portfolio'
        | 'cf-direct'
        | 'pw-pool'
        | 'pw-advised'
        | 'fo-formation'
        | 'inst-alts'
        | 'macro-growth'
        | 'macro-inflation'
        | 'macro-policy'
      )[]
    | null;
  insights?: (number | Insight)[] | null;
  /**
   * Lower numbers appear first where the website lists these items in a fixed order.
   */
  displayOrder?: number | null;
  /**
   * Editors: Draft or In review. Reviewers/Admins may approve and publish.
   */
  workflowStatus: 'draft' | 'review' | 'approved' | 'published' | 'archived';
  /**
   * Independent of workflow. Publishing does not change it. Only an Admin may confirm Approved corporate content.
   */
  contentClass: 'illustrative' | 'management_review' | 'approved_corporate';
  classificationConfirmedBy?: (number | null) | User;
  classificationConfirmedAt?: string | null;
  /**
   * Institutional byline, e.g. “Nusantara Investment Team”. Individual names only once approved.
   */
  author?: string | null;
  /**
   * After this date the item is withdrawn from the public site until re-reviewed.
   */
  reviewAt?: string | null;
  createdBy?: (number | null) | User;
  lastEditedBy?: (number | null) | User;
  submittedBy?: (number | null) | User;
  submittedAt?: string | null;
  approvedByUser?: (number | null) | User;
  approvedBy?: string | null;
  approvedAt?: string | null;
  approvedContentHash?: string | null;
  publishedAt?: string | null;
  /**
   * Set automatically when content changes. Shown on the website as the update date.
   */
  revisedAt?: string | null;
  /**
   * Preserved verbatim from the code-based content during migration. Never used to infer approval.
   */
  legacy?: {
    key?: string | null;
    status?: ('draft' | 'review' | 'approved' | 'published' | 'archived') | null;
    sample?: boolean | null;
    updatedAt?: string | null;
    importHash?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Source and licence. Required before public use.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * House interpretation. Editor/Approver separation applies: you cannot approve or publish your own submission.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nusantaraViews".
 */
export interface NusantaraView {
  id: number;
  /**
   * Stable id, e.g. “klci”. Matches the existing code-based view id.
   */
  key: string;
  subject: {
    kind: 'instrument' | 'assetClass' | 'indicator';
    instrument?:
      | (
          | 'klci'
          | 'sti'
          | 'jci'
          | 'nikkei'
          | 'hsi'
          | 'spx'
          | 'nasdaq'
          | 'usdmyr'
          | 'usdsgd'
          | 'usdidr'
          | 'sgdmyr'
          | 'eurusd'
          | 'usdcnh'
          | 'usdjpy'
          | 'us10y'
          | 'us2y'
          | 'mgs10y'
          | 'jgb10y'
          | 'sgs10y'
          | 'gold'
          | 'silver'
          | 'brent'
          | 'cpo'
          | 'copper'
        )
      | null;
    assetClass?: ('equities' | 'fx' | 'rates' | 'commodities') | null;
    indicator?:
      | (
          | 'am-assets'
          | 'am-alt-share'
          | 'pm-fundraising'
          | 'pm-undeployed'
          | 'pm-credit'
          | 'alt-real-assets'
          | 'alt-precious'
          | 'cf-portfolio'
          | 'cf-direct'
          | 'pw-pool'
          | 'pw-advised'
          | 'fo-formation'
          | 'inst-alts'
          | 'macro-growth'
          | 'macro-inflation'
          | 'macro-policy'
        )
      | null;
  };
  /**
   * One word or short phrase, e.g. “Selective”. Empty for indicator readings.
   */
  signal?: string | null;
  stance?: {
    scale?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    position?: number | null;
  };
  /**
   * One line used in cross-asset comparisons.
   */
  summary?: string | null;
  context: string;
  whatWeAreWatching?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  keyRisk?: string | null;
  whatWouldChangeOurView?: string | null;
  relatedMarkets?:
    | (
        | 'klci'
        | 'sti'
        | 'jci'
        | 'nikkei'
        | 'hsi'
        | 'spx'
        | 'nasdaq'
        | 'usdmyr'
        | 'usdsgd'
        | 'usdidr'
        | 'sgdmyr'
        | 'eurusd'
        | 'usdcnh'
        | 'usdjpy'
        | 'us10y'
        | 'us2y'
        | 'mgs10y'
        | 'jgb10y'
        | 'sgs10y'
        | 'gold'
        | 'silver'
        | 'brent'
        | 'cpo'
        | 'copper'
      )[]
    | null;
  relatedInsight?: (number | null) | Insight;
  /**
   * Short label shown with the view, e.g. “Resilience”.
   */
  theme?: string | null;
  /**
   * Dimensions this view reads into, most relevant first.
   */
  marketStateDimensions?: ('growth' | 'rates' | 'liquidity' | 'risk' | 'currencies' | 'commodities')[] | null;
  /**
   * Capabilities this market relates to (in addition to capabilities that list the market). Instrument views only.
   */
  capabilities?: (number | Capability)[] | null;
  /**
   * Lower numbers appear first where the website lists these items in a fixed order.
   */
  displayOrder?: number | null;
  /**
   * Editors: Draft or In review. A different Reviewer/Admin approves (no content changes in the same save), then publishes. You cannot approve or publish your own submission.
   */
  workflowStatus: 'draft' | 'review' | 'approved' | 'published' | 'archived';
  /**
   * Independent of workflow. Publishing does not change it. Only an Admin may confirm Approved corporate content.
   */
  contentClass: 'illustrative' | 'management_review' | 'approved_corporate';
  classificationConfirmedBy?: (number | null) | User;
  classificationConfirmedAt?: string | null;
  /**
   * Institutional byline, e.g. “Nusantara Investment Team”. Individual names only once approved.
   */
  author?: string | null;
  /**
   * Required to publish: a future date. After it the item is withdrawn from the public site until re-reviewed.
   */
  reviewAt?: string | null;
  createdBy?: (number | null) | User;
  lastEditedBy?: (number | null) | User;
  submittedBy?: (number | null) | User;
  submittedAt?: string | null;
  approvedByUser?: (number | null) | User;
  approvedBy?: string | null;
  approvedAt?: string | null;
  approvedContentHash?: string | null;
  publishedAt?: string | null;
  /**
   * Set automatically when content changes. Shown on the website as the update date.
   */
  revisedAt?: string | null;
  /**
   * Preserved verbatim from the code-based content during migration. Never used to infer approval.
   */
  legacy?: {
    key?: string | null;
    status?: ('draft' | 'review' | 'approved' | 'published' | 'archived') | null;
    sample?: boolean | null;
    updatedAt?: string | null;
    importHash?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * House interpretation, published as a whole edition. Editor/Approver separation applies.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketStateEditions".
 */
export interface MarketStateEdition {
  id: number;
  /**
   * e.g. “market-state-2026-10”.
   */
  key: string;
  /**
   * Edition name, e.g. “October 2026”.
   */
  edition: string;
  /**
   * Framing shown for sample/demonstration editions. Leave empty for a published house view.
   */
  framing?: {
    title?: string | null;
    note?: string | null;
  };
  dimensions?:
    | {
        dimension: 'growth' | 'rates' | 'liquidity' | 'risk' | 'currencies' | 'commodities';
        label: string;
        state: string;
        stance: {
          scale?:
            | {
                label: string;
                id?: string | null;
              }[]
            | null;
          position: number;
        };
        summary: string;
        watchItems?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        changeConditions: string;
        supportingMarkets?:
          | (
              | 'klci'
              | 'sti'
              | 'jci'
              | 'nikkei'
              | 'hsi'
              | 'spx'
              | 'nasdaq'
              | 'usdmyr'
              | 'usdsgd'
              | 'usdidr'
              | 'sgdmyr'
              | 'eurusd'
              | 'usdcnh'
              | 'usdjpy'
              | 'us10y'
              | 'us2y'
              | 'mgs10y'
              | 'jgb10y'
              | 'sgs10y'
              | 'gold'
              | 'silver'
              | 'brent'
              | 'cpo'
              | 'copper'
            )[]
          | null;
        relatedInsight?: (number | null) | Insight;
        capabilities?: (number | Capability)[] | null;
        dimensionUpdatedAt?: string | null;
        /**
         * Per-dimension status, preserved from the existing model.
         */
        dimensionStatus: 'draft' | 'review' | 'approved' | 'published' | 'archived';
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first where the website lists these items in a fixed order.
   */
  displayOrder?: number | null;
  /**
   * Editors: Draft or In review. A different Reviewer/Admin approves (no content changes in the same save), then publishes. You cannot approve or publish your own submission.
   */
  workflowStatus: 'draft' | 'review' | 'approved' | 'published' | 'archived';
  /**
   * Independent of workflow. Publishing does not change it. Only an Admin may confirm Approved corporate content.
   */
  contentClass: 'illustrative' | 'management_review' | 'approved_corporate';
  classificationConfirmedBy?: (number | null) | User;
  classificationConfirmedAt?: string | null;
  /**
   * Institutional byline, e.g. “Nusantara Investment Team”. Individual names only once approved.
   */
  author?: string | null;
  /**
   * Required to publish: a future date. After it the item is withdrawn from the public site until re-reviewed.
   */
  reviewAt?: string | null;
  createdBy?: (number | null) | User;
  lastEditedBy?: (number | null) | User;
  submittedBy?: (number | null) | User;
  submittedAt?: string | null;
  approvedByUser?: (number | null) | User;
  approvedBy?: string | null;
  approvedAt?: string | null;
  approvedContentHash?: string | null;
  publishedAt?: string | null;
  /**
   * Set automatically when content changes. Shown on the website as the update date.
   */
  revisedAt?: string | null;
  /**
   * Preserved verbatim from the code-based content during migration. Never used to infer approval.
   */
  legacy?: {
    key?: string | null;
    status?: ('draft' | 'review' | 'approved' | 'published' | 'archived') | null;
    sample?: boolean | null;
    updatedAt?: string | null;
    importHash?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signals".
 */
export interface Signal {
  id: number;
  /**
   * Stable id.
   */
  key: string;
  date: string;
  /**
   * Short theme label shown with the signal.
   */
  theme: string;
  headline: string;
  reading: string;
  instrument?:
    | (
        | 'klci'
        | 'sti'
        | 'jci'
        | 'nikkei'
        | 'hsi'
        | 'spx'
        | 'nasdaq'
        | 'usdmyr'
        | 'usdsgd'
        | 'usdidr'
        | 'sgdmyr'
        | 'eurusd'
        | 'usdcnh'
        | 'usdjpy'
        | 'us10y'
        | 'us2y'
        | 'mgs10y'
        | 'jgb10y'
        | 'sgs10y'
        | 'gold'
        | 'silver'
        | 'brent'
        | 'cpo'
        | 'copper'
      )
    | null;
  insight?: (number | null) | Insight;
  /**
   * Lower numbers appear first where the website lists these items in a fixed order.
   */
  displayOrder?: number | null;
  /**
   * Editors: Draft or In review. Reviewers/Admins may approve and publish.
   */
  workflowStatus: 'draft' | 'review' | 'approved' | 'published' | 'archived';
  /**
   * Independent of workflow. Publishing does not change it. Only an Admin may confirm Approved corporate content.
   */
  contentClass: 'illustrative' | 'management_review' | 'approved_corporate';
  classificationConfirmedBy?: (number | null) | User;
  classificationConfirmedAt?: string | null;
  /**
   * Institutional byline, e.g. “Nusantara Investment Team”. Individual names only once approved.
   */
  author?: string | null;
  /**
   * Required to publish: a future date. After it the item is withdrawn from the public site until re-reviewed.
   */
  reviewAt?: string | null;
  createdBy?: (number | null) | User;
  lastEditedBy?: (number | null) | User;
  submittedBy?: (number | null) | User;
  submittedAt?: string | null;
  approvedByUser?: (number | null) | User;
  approvedBy?: string | null;
  approvedAt?: string | null;
  approvedContentHash?: string | null;
  publishedAt?: string | null;
  /**
   * Set automatically when content changes. Shown on the website as the update date.
   */
  revisedAt?: string | null;
  /**
   * Preserved verbatim from the code-based content during migration. Never used to infer approval.
   */
  legacy?: {
    key?: string | null;
    status?: ('draft' | 'review' | 'approved' | 'published' | 'archived') | null;
    sample?: boolean | null;
    updatedAt?: string | null;
    importHash?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Full version history is kept. A final legal approver has not yet been designated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legalPages".
 */
export interface LegalPage {
  id: number;
  /**
   * Fixed set of legal pages at /legal/[page].
   */
  slug: 'important-information' | 'disclaimer' | 'privacy' | 'terms';
  title: string;
  summary: string;
  sections?:
    | {
        heading: string;
        body?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  versioning?: {
    /**
     * e.g. “v1.0”.
     */
    versionLabel?: string | null;
    effectiveDate?: string | null;
    changeNote?: string | null;
    /**
     * Notes only. No final legal approver is designated yet.
     */
    legalReviewNotes?: string | null;
  };
  /**
   * Lower numbers appear first where the website lists these items in a fixed order.
   */
  displayOrder?: number | null;
  /**
   * Editors: Draft or In review. Reviewers/Admins may approve and publish.
   */
  workflowStatus: 'draft' | 'review' | 'approved' | 'published' | 'archived';
  /**
   * Independent of workflow. Publishing does not change it. Only an Admin may confirm Approved corporate content.
   */
  contentClass: 'illustrative' | 'management_review' | 'approved_corporate';
  classificationConfirmedBy?: (number | null) | User;
  classificationConfirmedAt?: string | null;
  /**
   * Institutional byline, e.g. “Nusantara Investment Team”. Individual names only once approved.
   */
  author?: string | null;
  /**
   * After this date the item is withdrawn from the public site until re-reviewed.
   */
  reviewAt?: string | null;
  createdBy?: (number | null) | User;
  lastEditedBy?: (number | null) | User;
  submittedBy?: (number | null) | User;
  submittedAt?: string | null;
  approvedByUser?: (number | null) | User;
  approvedBy?: string | null;
  approvedAt?: string | null;
  approvedContentHash?: string | null;
  publishedAt?: string | null;
  /**
   * Set automatically when content changes. Shown on the website as the update date.
   */
  revisedAt?: string | null;
  /**
   * Preserved verbatim from the code-based content during migration. Never used to infer approval.
   */
  legacy?: {
    key?: string | null;
    status?: ('draft' | 'review' | 'approved' | 'published' | 'archived') | null;
    sample?: boolean | null;
    updatedAt?: string | null;
    importHash?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditLog".
 */
export interface AuditLog {
  id: number;
  at: string;
  action:
    | 'create'
    | 'edit'
    | 'submit'
    | 'approve'
    | 'publish'
    | 'archive'
    | 'classify'
    | 'restore'
    | 'discard'
    | 'delete'
    | 'user';
  collection: string;
  documentId: string;
  title?: string | null;
  summary: string;
  user?: (number | null) | User;
  userEmail?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null)
    | ({
        relationTo: 'nusantaraViews';
        value: number | NusantaraView;
      } | null)
    | ({
        relationTo: 'marketStateEditions';
        value: number | MarketStateEdition;
      } | null)
    | ({
        relationTo: 'signals';
        value: number | Signal;
      } | null)
    | ({
        relationTo: 'themes';
        value: number | Theme;
      } | null)
    | ({
        relationTo: 'capabilities';
        value: number | Capability;
      } | null)
    | ({
        relationTo: 'legalPages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'auditLog';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  subtitle?: T;
  category?: T;
  date?: T;
  summary?: T;
  executiveSummary?:
    | T
    | {
        text?: T;
        id?: T;
      };
  keyTakeaways?:
    | T
    | {
        text?: T;
        id?: T;
      };
  body?:
    | T
    | {
        heading?:
          | T
          | {
              text?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              ordered?: T;
              id?: T;
              blockName?: T;
            };
        pullquote?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        layer?:
          | T
          | {
              layer?: T;
              title?: T;
              body?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        table?:
          | T
          | {
              caption?: T;
              columns?: T;
              rows?:
                | T
                | {
                    cells?: T;
                    id?: T;
                  };
              note?: T;
              layer?: T;
              id?: T;
              blockName?: T;
            };
        comparison?:
          | T
          | {
              caption?: T;
              left?: T;
              right?: T;
              rows?:
                | T
                | {
                    leftText?: T;
                    rightText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        chart?:
          | T
          | {
              caption?: T;
              kind?: T;
              xLabels?: T;
              series?:
                | T
                | {
                    seriesKey?: T;
                    label?: T;
                    values?: T;
                    id?: T;
                  };
              unit?: T;
              decimals?: T;
              source?: T;
              illustrative?: T;
              id?: T;
              blockName?: T;
            };
        scenario?:
          | T
          | {
              scenario?:
                | T
                | {
                    scenarioKey?: T;
                    title?: T;
                    metric?: T;
                    unit?: T;
                    decimals?: T;
                    baseYear?: T;
                    baseValue?: T;
                    years?: T;
                    periodLabels?: T;
                    downside?:
                      | T
                      | {
                          label?: T;
                          assumption?: T;
                          values?: T;
                          rate?: T;
                        };
                    base?:
                      | T
                      | {
                          label?: T;
                          assumption?: T;
                          values?: T;
                          rate?: T;
                        };
                    upside?:
                      | T
                      | {
                          label?: T;
                          assumption?: T;
                          values?: T;
                          rate?: T;
                        };
                    period?: T;
                    dataSource?: T;
                    methodology?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
      };
  methodology?: T;
  sources?:
    | T
    | {
        label?: T;
        detail?: T;
        url?: T;
        provider?: T;
        publishedAt?: T;
        retrievedAt?: T;
        licensingNote?: T;
        methodology?: T;
        id?: T;
      };
  featured?: T;
  heroMotif?: T;
  tags?: T;
  related?: T;
  markets?: T;
  themes?: T;
  assetClasses?: T;
  capabilities?: T;
  marketStateDimensions?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  displayOrder?: T;
  workflowStatus?: T;
  contentClass?: T;
  classificationConfirmedBy?: T;
  classificationConfirmedAt?: T;
  author?: T;
  reviewAt?: T;
  createdBy?: T;
  lastEditedBy?: T;
  submittedBy?: T;
  submittedAt?: T;
  approvedByUser?: T;
  approvedBy?: T;
  approvedAt?: T;
  approvedContentHash?: T;
  publishedAt?: T;
  revisedAt?: T;
  legacy?:
    | T
    | {
        key?: T;
        status?: T;
        sample?: T;
        updatedAt?: T;
        importHash?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nusantaraViews_select".
 */
export interface NusantaraViewsSelect<T extends boolean = true> {
  key?: T;
  subject?:
    | T
    | {
        kind?: T;
        instrument?: T;
        assetClass?: T;
        indicator?: T;
      };
  signal?: T;
  stance?:
    | T
    | {
        scale?:
          | T
          | {
              label?: T;
              id?: T;
            };
        position?: T;
      };
  summary?: T;
  context?: T;
  whatWeAreWatching?:
    | T
    | {
        text?: T;
        id?: T;
      };
  keyRisk?: T;
  whatWouldChangeOurView?: T;
  relatedMarkets?: T;
  relatedInsight?: T;
  theme?: T;
  marketStateDimensions?: T;
  capabilities?: T;
  displayOrder?: T;
  workflowStatus?: T;
  contentClass?: T;
  classificationConfirmedBy?: T;
  classificationConfirmedAt?: T;
  author?: T;
  reviewAt?: T;
  createdBy?: T;
  lastEditedBy?: T;
  submittedBy?: T;
  submittedAt?: T;
  approvedByUser?: T;
  approvedBy?: T;
  approvedAt?: T;
  approvedContentHash?: T;
  publishedAt?: T;
  revisedAt?: T;
  legacy?:
    | T
    | {
        key?: T;
        status?: T;
        sample?: T;
        updatedAt?: T;
        importHash?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketStateEditions_select".
 */
export interface MarketStateEditionsSelect<T extends boolean = true> {
  key?: T;
  edition?: T;
  framing?:
    | T
    | {
        title?: T;
        note?: T;
      };
  dimensions?:
    | T
    | {
        dimension?: T;
        label?: T;
        state?: T;
        stance?:
          | T
          | {
              scale?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              position?: T;
            };
        summary?: T;
        watchItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        changeConditions?: T;
        supportingMarkets?: T;
        relatedInsight?: T;
        capabilities?: T;
        dimensionUpdatedAt?: T;
        dimensionStatus?: T;
        id?: T;
      };
  displayOrder?: T;
  workflowStatus?: T;
  contentClass?: T;
  classificationConfirmedBy?: T;
  classificationConfirmedAt?: T;
  author?: T;
  reviewAt?: T;
  createdBy?: T;
  lastEditedBy?: T;
  submittedBy?: T;
  submittedAt?: T;
  approvedByUser?: T;
  approvedBy?: T;
  approvedAt?: T;
  approvedContentHash?: T;
  publishedAt?: T;
  revisedAt?: T;
  legacy?:
    | T
    | {
        key?: T;
        status?: T;
        sample?: T;
        updatedAt?: T;
        importHash?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signals_select".
 */
export interface SignalsSelect<T extends boolean = true> {
  key?: T;
  date?: T;
  theme?: T;
  headline?: T;
  reading?: T;
  instrument?: T;
  insight?: T;
  displayOrder?: T;
  workflowStatus?: T;
  contentClass?: T;
  classificationConfirmedBy?: T;
  classificationConfirmedAt?: T;
  author?: T;
  reviewAt?: T;
  createdBy?: T;
  lastEditedBy?: T;
  submittedBy?: T;
  submittedAt?: T;
  approvedByUser?: T;
  approvedBy?: T;
  approvedAt?: T;
  approvedContentHash?: T;
  publishedAt?: T;
  revisedAt?: T;
  legacy?:
    | T
    | {
        key?: T;
        status?: T;
        sample?: T;
        updatedAt?: T;
        importHash?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes_select".
 */
export interface ThemesSelect<T extends boolean = true> {
  key?: T;
  title?: T;
  statement?: T;
  insights?: T;
  instruments?: T;
  indicators?: T;
  displayOrder?: T;
  workflowStatus?: T;
  contentClass?: T;
  classificationConfirmedBy?: T;
  classificationConfirmedAt?: T;
  author?: T;
  reviewAt?: T;
  createdBy?: T;
  lastEditedBy?: T;
  submittedBy?: T;
  submittedAt?: T;
  approvedByUser?: T;
  approvedBy?: T;
  approvedAt?: T;
  approvedContentHash?: T;
  publishedAt?: T;
  revisedAt?: T;
  legacy?:
    | T
    | {
        key?: T;
        status?: T;
        sample?: T;
        updatedAt?: T;
        importHash?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capabilities_select".
 */
export interface CapabilitiesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  capabilityStatus?: T;
  stage?: T;
  summary?: T;
  overview?: T;
  approach?: T;
  opportunitySet?:
    | T
    | {
        text?: T;
        id?: T;
      };
  riskConsiderations?:
    | T
    | {
        text?: T;
        id?: T;
      };
  timeHorizon?: T;
  characteristics?:
    | T
    | {
        text?: T;
        id?: T;
      };
  role?: T;
  profile?:
    | T
    | {
        liquidity?: T;
        income?: T;
        complexity?: T;
        valuationFrequency?: T;
      };
  markets?: T;
  indicators?: T;
  insights?: T;
  displayOrder?: T;
  workflowStatus?: T;
  contentClass?: T;
  classificationConfirmedBy?: T;
  classificationConfirmedAt?: T;
  author?: T;
  reviewAt?: T;
  createdBy?: T;
  lastEditedBy?: T;
  submittedBy?: T;
  submittedAt?: T;
  approvedByUser?: T;
  approvedBy?: T;
  approvedAt?: T;
  approvedContentHash?: T;
  publishedAt?: T;
  revisedAt?: T;
  legacy?:
    | T
    | {
        key?: T;
        status?: T;
        sample?: T;
        updatedAt?: T;
        importHash?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legalPages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  summary?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  versioning?:
    | T
    | {
        versionLabel?: T;
        effectiveDate?: T;
        changeNote?: T;
        legalReviewNotes?: T;
      };
  displayOrder?: T;
  workflowStatus?: T;
  contentClass?: T;
  classificationConfirmedBy?: T;
  classificationConfirmedAt?: T;
  author?: T;
  reviewAt?: T;
  createdBy?: T;
  lastEditedBy?: T;
  submittedBy?: T;
  submittedAt?: T;
  approvedByUser?: T;
  approvedBy?: T;
  approvedAt?: T;
  approvedContentHash?: T;
  publishedAt?: T;
  revisedAt?: T;
  legacy?:
    | T
    | {
        key?: T;
        status?: T;
        sample?: T;
        updatedAt?: T;
        importHash?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditLog_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  at?: T;
  action?: T;
  collection?: T;
  documentId?: T;
  title?: T;
  summary?: T;
  user?: T;
  userEmail?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Unconfirmed corporate facts stay empty. Do not enter placeholders.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Leave empty until confirmed by management. Nothing here is shown publicly in B0.
   */
  entity?: {
    legalName?: string | null;
    registrationNumber?: string | null;
    registeredAddress?: string | null;
  };
  /**
   * Leave empty until confirmed by management. Nothing here is shown publicly in B0.
   */
  licences?:
    | {
        regulator: string;
        licence: string;
        reference?: string | null;
        jurisdiction?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty until confirmed by management. Nothing here is shown publicly in B0.
   */
  offices?:
    | {
        city: string;
        address?: string | null;
        phone?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty until confirmed by management. Nothing here is shown publicly in B0.
   */
  leadership?:
    | {
        name: string;
        role: string;
        biography?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty until confirmed by management. Nothing here is shown publicly in B0.
   */
  contact?: {
    generalEmail?: string | null;
    phone?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  entity?:
    | T
    | {
        legalName?: T;
        registrationNumber?: T;
        registeredAddress?: T;
      };
  licences?:
    | T
    | {
        regulator?: T;
        licence?: T;
        reference?: T;
        jurisdiction?: T;
        id?: T;
      };
  offices?:
    | T
    | {
        city?: T;
        address?: T;
        phone?: T;
        id?: T;
      };
  leadership?:
    | T
    | {
        name?: T;
        role?: T;
        biography?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        generalEmail?: T;
        phone?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}